openapi: 3.0.3
info:
  title: News Aggregator API
  description: API for aggregating news articles from multiple sources.
  version: 1.0.0
paths:
  /articles:
    get:
      summary: Retrieve a list of articles
      operationId: getArticles
      parameters:
        - name: page
          in: query
          required: false
          description: Page number for pagination
          schema:
            type: integer
            example: 1
        - name: limit
          in: query
          required: false
          description: Number of articles to return per page
          schema:
            type: integer
            example: 10
      responses:
        "200":
          description: A list of articles
          content:
            application/json:
              schema:
                type: object
                properties:
                  articles:
                    type: array
                    items:
                      $ref: "#/components/schemas/Article"
                  total:
                    type: integer
                  page:
                    type: integer
                    example: 1
                  limit:
                    type: integer
                    example: 10
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error

    post:
      summary: Create a new article
      operationId: createArticle
      security:
        - OAuth2: [editor]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ArticleInput"
      responses:
        "201":
          description: Article created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Article"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error

  /articles/{articleId}:
    get:
      summary: Retrieve a specific article by ID
      operationId: getArticleById
      parameters:
        - name: articleId
          in: path
          required: true
          description: The ID of the article
          schema:
            type: string
      responses:
        "200":
          description: Article details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Article"
        "404":
          description: Article not found
        "500":
          description: Internal Server Error

    put:
      summary: Update an existing article
      operationId: updateArticle
      security:
        - OAuth2: [editor]
      parameters:
        - name: articleId
          in: path
          required: true
          description: The ID of the article to be updated
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ArticleInput"
      responses:
        "200":
          description: Article updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Article"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Article not found
        "500":
          description: Internal Server Error

    delete:
      summary: Delete an article
      operationId: deleteArticle
      security:
        - OAuth2: [admin]
      parameters:
        - name: articleId
          in: path
          required: true
          description: The ID of the article to delete
          schema:
            type: string
      responses:
        "204":
          description: Article deleted successfully
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Article not found
        "500":
          description: Internal Server Error

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        password:
          tokenUrl: /token
          scopes:
            reader: Read articles
            editor: Edit articles
            admin: Administrative actions

  schemas:
    Article:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
          example: "Breaking News: Example Article"
        content:
          type: string
          example: "This is the content of the example article."
        source:
          type: string
          example: "Example News Source"
        published_at:
          type: string
          format: date-time
          example: "2023-10-23T14:20:00Z"

    ArticleInput:
      type: object
      required:
        - title
        - content
        - source
      properties:
        title:
          type: string
          example: "Breaking News: Example Article"
        content:
          type: string
          example: "This is the content of the example article."
        source:
          type: string
          example: "Example News Source"

  responses:
    UnauthorizedError:
      description: Unauthorized access
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
                example: "Not authenticated"

    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
                example: "Invalid input data"

    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
                example: "Article not found"

    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
                example: "An unexpected error occurred"
